const countryList = {
    AUD: { code: "AU", name: "Australia" },
    BGN: { code: "BG", name: "Bulgaria" },
    BRL: { code: "BR", name: "Brazil" },
    CAD: { code: "CA", name: "Canada" },
    CHF: { code: "CH", name: "Switzerland" },
    CNY: { code: "CN", name: "China" },
    CZK: { code: "CZ", name: "Czech Republic" },
    DKK: { code: "DK", name: "Denmark" },
    EUR: { code: "EU", name: "European Union" },
    GBP: { code: "GB", name: "United Kingdom" },
    HKD: { code: "HK", name: "Hong Kong" },
    HUF: { code: "HU", name: "Hungary" },
    IDR: { code: "ID", name: "Indonesia" },
    ILS: { code: "IL", name: "Israel" },
    INR: { code: "IN", name: "India" },
    ISK: { code: "IS", name: "Iceland" },
    JPY: { code: "JP", name: "Japan" },
    KRW: { code: "KR", name: "South Korea" },
    MXN: { code: "MX", name: "Mexico" },
    MYR: { code: "MY", name: "Malaysia" },
    NOK: { code: "NO", name: "Norway" },
    NZD: { code: "NZ", name: "New Zealand" },
    PHP: { code: "PH", name: "Philippines" },
    PLN: { code: "PL", name: "Poland" },
    RON: { code: "RO", name: "Romania" },
    SEK: { code: "SE", name: "Sweden" },
    SGD: { code: "SG", name: "Singapore" },
    THB: { code: "TH", name: "Thailand" },
    TRY: { code: "TR", name: "Turkey" },
    USD: { code: "US", name: "United States" },
    ZAR: { code: "ZA", name: "South Africa" }
};
